# scripts/embed_spv.cmake

# Expected defines: INPUT_FILE, OUTPUT_FILE, NAMESPACE

# 1. Read the SPIR-V binary as a hex string (e.g., "03022307...")
file(READ "${INPUT_FILE}" HEX_CONTENT HEX)

# 2. Format it as 32-bit integers (0x07230203, ...)
#    We capture 4 bytes (8 hex chars) at a time: (..)(..)(..)(..)
#    And rewrite them in reverse order for Little Endian: 0x\4\3\2\1
string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1, " HEX_FORMATTED "${HEX_CONTENT}")

# 3. Write the C++ header
file(WRITE "${OUTPUT_FILE}" "// Generated by embed_spv.cmake\n")
file(APPEND "${OUTPUT_FILE}" "#pragma once\n\n")
file(APPEND "${OUTPUT_FILE}" "#include <cstddef>\n")

file(APPEND "${OUTPUT_FILE}" "namespace ${NAMESPACE} \n{\n")

# This removes the need for reinterpret_cast.
file(APPEND "${OUTPUT_FILE}" "	constexpr uint32_t code[] = { ${HEX_FORMATTED} };\n")

# Note: sizeof(code) returns total bytes, which is exactly what codeSize expects.
file(APPEND "${OUTPUT_FILE}" "	constexpr size_t size = sizeof(code);\n")
file(APPEND "${OUTPUT_FILE}" "} // namespace ${NAMESPACE}\n")
