# scripts/embed_spv.cmake

# Expected defines: INPUT_FILE, OUTPUT_FILE, NAMESPACE

# 1. Read the SPIR-V binary as a hex string
file(READ "${INPUT_FILE}" HEX_CONTENT HEX)

# 2. Format it as 0x00, 0x01, ...
string(REGEX REPLACE "(..)" "0x\\1, " HEX_FORMATTED "${HEX_CONTENT}")

# 3. Write the C++ header
file(WRITE "${OUTPUT_FILE}" "// Generated by embed_spv.cmake\n")
file(APPEND "${OUTPUT_FILE}" "#pragma once\n\n")
file(APPEND "${OUTPUT_FILE}" "#include <cstddef>\n")
file(APPEND "${OUTPUT_FILE}" "#include <cstdint>\n\n") # Needed for alignas logic if we were using uint32_t, but alignas is C++ keyword

file(APPEND "${OUTPUT_FILE}" "namespace ${NAMESPACE} {\n\n")

# CHANGE: Add alignas(4) to ensure the char array is safe to cast to uint32_t*
file(APPEND "${OUTPUT_FILE}" "    alignas(4) constexpr unsigned char code[] = { ${HEX_FORMATTED} };\n")

file(APPEND "${OUTPUT_FILE}" "    constexpr size_t size = sizeof(code);\n\n")
file(APPEND "${OUTPUT_FILE}" "} // namespace ${NAMESPACE}\n")
